spring:
  profiles:
    active: release
  datasource:
    url: jdbc:postgresql://localhost:5432/caching-example
    username: caching-username
    password: caching-password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none